# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{johnny}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micheil Smith"]
  s.date = %q{2010-03-29}
  s.default_executable = %q{johnny}
  s.description = %q{Watches directories and converts markdown documents to other formats through erb templates}
  s.email = %q{micheil@brandedcode.com}
  s.executables = ["johnny"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "VERSION",
     "bin/johnny",
     "lib/johnny.rb",
     "lib/johnny/command.rb",
     "lib/johnny/config.rb",
     "lib/johnny/converter.rb",
     "lib/johnny/converters/html.rb",
     "lib/johnny/converters/markdown.rb",
     "lib/johnny/converters/sass.rb",
     "lib/johnny/rack.rb",
     "lib/johnny/watcher.rb",
     "templates/layout.html",
     "templates/layout.mu",
     "templates/style.sass"
  ]
  s.homepage = %q{http://github.com/miksago/johnny}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Watches directories and converts markdown documents to other formats}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<optparse>, [">= 0"])
      s.add_runtime_dependency(%q<fssm>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
    else
      s.add_dependency(%q<optparse>, [">= 0"])
      s.add_dependency(%q<fssm>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
    end
  else
    s.add_dependency(%q<optparse>, [">= 0"])
    s.add_dependency(%q<fssm>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
  end
end

